---
- name: Configure Docker and Jenkins Permissions
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add Jenkins to Docker Group
      command: usermod -aG docker jenkins

    - name: Restart Jenkins Service (First Time)
      service:
        name: jenkins
        state: restarted

    - name: Configure Sudoers for Jenkins
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^jenkins ALL=\(ALL:ALL\) NOPASSWD: ALL$'
        line: 'jenkins ALL=(ALL:ALL) NOPASSWD: ALL'

    - name: Restart Jenkins Service (Final Time)
      service:
        name: jenkins
        state: restarted
